# workspace 6
windowrulev2 = workspace 6, class:^(steam_app_.*)$
windowrulev2 = fullscreen, class:^(steam_app_.*)$

# Extra autostart processes
exec-once = hyprctl dispatch workspace 1 && uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"

exec-once = hyprctl dispatch workspace 2 && omarchy-launch-browser

exec-once = hyprctl dispatch workspace 5 && omarchy-launch-webapp WhatsApp "https://web.whatsapp.com/"
exec-once = hyprctl dispatch workspace 5 && omarchy-launch-webapp Discord "https://discord.com/app"
exec-once = hyprctl dispatch workspace 5 && omarchy-launch-webapp Music "https://music.youtube.com/"

