"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$all\
$line_break$character"""

[aws]
disabled = true

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[fill]
symbol = " "

[bun]
symbol = "󰏗 "
format = "[$symbol($version )]($style)"

[c]
symbol = " "
format = "[$symbol($version )]($style)"

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "
format = "[$symbol($version )]($style)"

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "
format = "[$symbol($version )]($style)"

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "
format = "[$symbol($version )]($style)"

[kotlin]
symbol = " "
format = "[$symbol($version )]($style)"

[lua]
symbol = " "
format = "[$symbol($version )]($style)"

[memory_usage]
symbol = "󰍛 "
format = "[$symbol($version )]($style)"

[meson]
symbol = "󰔷 "
format = "[$symbol($version )]($style)"

[nodejs]
symbol = " "
format = "[$symbol($version )]($style)"

[package]
symbol = "󰏗 "
format = "[$symbol($version )]($style)"

[python]
symbol = " "
format = "[$symbol($version )]($style)"

[rust]
symbol = " "
format = "[$symbol($version )]($style)"

[zig]
symbol = " "
format = "[$symbol($version )]($style)"
