import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
family = "JetBrainsMono NF"

[scrolling]
history = 2000

[window]
decorations = "buttonless"
opacity = 0.98

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 14
y = 14
