import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[font]
size = 20

[font.normal]
family = "JetBrainsMono Nerd Font"

[scrolling]
history = 2000

[window]
decorations = "buttonless"
dynamic_padding = true

[window.padding]
x = 8
y = 8

[window.dimensions]
columns = 120
lines = 40
