require("config/options")
require("config/keymap")
require("config/statusline")
require("config/autocmds")
require("config/spell")

require("plugins/theme")
require("plugins/gitsigns")
require("plugins/harpoon")
require("plugins/snacks")
require("plugins/mini")
require("plugins/lsp")
